const pptxgen = require("pptxgenjs");
const path    = require("path");
const fs      = require("fs");

/*
|--------------------------------------------------------------------------
| ENSURE REPORTS DIRECTORY EXISTS
|--------------------------------------------------------------------------
*/
const ensureReportsDir = () => {
  const dir = path.join(process.cwd(), "reports")
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true })
  }
  return dir
}

/*
|--------------------------------------------------------------------------
| GENERATE PPT
|--------------------------------------------------------------------------
*/
const generatePPT = async ({
  title       = "Pearl Analytics Report",
  author      = "Pearl",
  slides      = [],
  includeDate = true
}) => {

  const ppt     = new pptxgen()
  ppt.author    = author
  ppt.company   = "Pearl Analytics"
  ppt.subject   = "Analytics Report"
  ppt.title     = title

  // ── Default slides if none provided ─────────────────────────────────
  if (slides.length === 0) {
    slides = [
      {
        title:   title,
        content: includeDate
          ? `Generated: ${new Date().toLocaleString()}`
          : "",
        type:    "title"
      },
      { title: "Correlation Analysis",  content: "Correlation module integrated successfully", type: "content" },
      { title: "Outlier Analysis",       content: "Outlier module integrated successfully",      type: "content" },
      { title: "Infographics",           content: "Bar, Line, Pie, Scatter, Heatmap charts",    type: "content" },
      { title: "Executive Summary",      content: "Presentation generated by Pearl Analytics",  type: "content" },
    ]
  }

  // ── Build slides ─────────────────────────────────────────────────────
  slides.forEach((slideData, index) => {
    const slide = ppt.addSlide()

    // Title
    slide.addText(slideData.title || `Slide ${index + 1}`, {
      x:        0.5,
      y:        0.5,
      w:        9,
      h:        0.8,
      fontSize: index === 0 ? 28 : 22,
      bold:     true,
      color:    "363B5A"
    })

    // Content text
    if (slideData.content) {
      slide.addText(slideData.content, {
        x:        0.5,
        y:        1.5,
        w:        9,
        h:        4,
        fontSize: 14,
        color:    "555555",
        wrap:     true
      })
    }

    // Chart data if provided
    if (slideData.chartData) {
      try {
        slide.addChart(ppt.ChartType.bar, slideData.chartData, {
          x: 0.5, y: 2, w: 9, h: 4
        })
      } catch (e) {
        // Chart rendering failed — add text note instead
        slide.addText("Chart data provided but could not be rendered", {
          x: 0.5, y: 2, w: 9, h: 1, fontSize: 12, color: "999999"
        })
      }
    }

    // Bullet points if provided
    if (Array.isArray(slideData.bullets) && slideData.bullets.length > 0) {
      const bulletText = slideData.bullets.map(b => ({ text: b, options: { bullet: true } }))
      slide.addText(bulletText, {
        x:        0.5,
        y:        1.5,
        w:        9,
        h:        4,
        fontSize: 14,
        color:    "555555"
      })
    }
  })

  // ── Save file ────────────────────────────────────────────────────────
  const reportsDir = ensureReportsDir()
  const fileName   = `report-${Date.now()}.pptx`
  const filePath   = path.join(reportsDir, fileName)

  await ppt.writeFile({ fileName: filePath })

  return {
    fileName,
    filePath,
    slideCount: slides.length,
    generatedAt: new Date().toISOString()
  }
}

module.exports = { generatePPT }